name: 🐛Bug report
description: Short description of how to trigger this bug
labels:
  - bug
body:
  - type: input
    id: app-version
    attributes:
      label: Version of SeryMusic
      description: Found in Settings > About
      placeholder: v.1.0.0, v.1.1.0, etc.
    validations:
      required: true
  - type: input
    id: android-version
    attributes:
      label: Android version
      placeholder: '16'
    validations:
      required: true
  - type: textarea
    id: bug-trigger
    attributes:
      label: Tell us how to trigger this bug
      description: 'Each step should be on its own line. You can use simple sentences like:'
      placeholder: 1. Open SeryMusic 2. Click on A  3. Click on B 4. Boom! Crash happens
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
  - type: textarea
    id: log
    attributes:
      label: Logs
      description: Crash logs can be copied by long-pressing the app's icon > "Copy crash log to clipboard"
      render: text
